### ISSUE TITLE
重启插件发生故障：RuntimeError

### ISSUE THREAD

**Issue by ShadowGhost0x1a0** [18870/nonebot-plugin-reboot#2]
猜测会不会有可能跟pip install或者nb-cli的插件安装相关。理论上这两种应该没有差别？
基于这个猜测通过nb-cli安装了nonebot-plugin-reboot，经过测试，命令成功响应，但是发生了RunTimeError
python bot.py的运行记录：
```
PS C:\Users\Administrator\Desktop\Koharu2> python bot.py
06-29 12:20:58 [SUCCESS] nonebot | NoneBot is initializing...
06-29 12:20:58 [INFO] nonebot | Current Env: dev
06-29 12:20:58 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'897528497'}, 'nickname': {'Miyu'}, 'command_start': {''}, 'com
mand_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev
'}
06-29 12:20:58 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-29 12:20:58 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_reboot"
06-29 12:20:59 [SUCCESS] nonebot | NoneBot is initializing...
06-29 12:20:59 [INFO] nonebot | Current Env: dev
06-29 12:20:59 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'897528497'}, 'nickname': {'Miyu'}, 'command_start': {''}, 'com
mand_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev
'}
06-29 12:20:59 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_reboot"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "public"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "tianqi"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "guess_test"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_log_updater"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "maimaidx"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "laugh"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_maimaidx_aliases"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "util"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "csvtest"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "changer"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "permission_grant"
06-29 12:20:59 [SUCCESS] nonebot | Succeeded to import "updater_core"
06-29 12:20:59 [SUCCESS] nonebot | Running NoneBot...
06-29 12:20:59 [DEBUG] nonebot | Loaded adapters: OneBot V11
06-29 12:20:59 [INFO] uvicorn | Will watch for changes in these directories: ['C:\\Users\\Administrator\\Desktop\\Koharu
2']
06-29 12:20:59 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
06-29 12:21:00 [INFO] uvicorn | Started reloader process [2220] using watchgod
06-29 12:21:00 [SUCCESS] nonebot | NoneBot is initializing...
06-29 12:21:00 [INFO] nonebot | Current Env: dev
06-29 12:21:00 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'897528497'}, 'nickname': {'Miyu'}, 'command_start': {''}, 'com
mand_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': Tru
e}
06-29 12:21:00 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-29 12:21:00 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_reboot"
06-29 12:21:00 [SUCCESS] nonebot | Succeeded to import "guess_test"
06-29 12:21:00 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_maimaidx_aliases"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "maimaidx"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "laugh"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_log_updater"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "public"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "tianqi"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "csvtest"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "changer"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "util"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "permission_grant"
06-29 12:21:01 [SUCCESS] nonebot | Succeeded to import "updater_core"
06-29 12:21:01 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
06-29 12:21:01 [INFO] uvicorn | Started server process [624]
06-29 12:21:01 [INFO] uvicorn | Waiting for application startup.
06-29 12:21:01 [INFO] uvicorn | Application startup complete.
06-29 12:21:01 [INFO] uvicorn | ('127.0.0.1', 62182) - "WebSocket /onebot/v11/ws" [accepted]
06-29 12:21:01 [INFO] nonebot | OneBot V11 | Bot 3603946386 connected
06-29 12:21:01 [INFO] websockets | connection open
06-29 12:21:18 [SUCCESS] nonebot | ONEBOT V11 3603946386 | [message.private.friend]: Message 1606916880 from 897528497 "
重启"
06-29 12:21:18 [DEBUG] nonebot | Running PreProcessors...
06-29 12:21:18 [DEBUG] nonebot | Checking for matchers in priority 1...
06-29 12:21:18 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_reboot.command, type=message, prio
rity=1, temp=False>
06-29 12:21:18 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_reboot.command, type=message, priority=1,
temp=False>
06-29 12:21:18 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x0000004647EDD7E0>, params=[ModelField(
name='event', type=PrivateMessageEvent, required=True)], parameterless=[]>
06-29 12:21:18 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_reboot.command, type=message, priority=1, temp=Fals
e> running complete
06-29 12:21:18 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_reboot.command, type=message, priority=1,
temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn
_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main

    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bo
otstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run

    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\subprocess.py", line 76
, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in
 run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146,
in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196,
in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", l
ine 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", l
ine 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.p
y", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\command.p
y", line 16, in _
    Reloader.reload()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\reloader.
py", line 18, in reload
    raise RuntimeError()
RuntimeError
06-29 12:21:18 [DEBUG] nonebot | Stop event propagation
```
error.log如下：
```
06-29 12:21:18 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_reboot.command, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 208
               │     └ 3
               └ <function _main at 0x000000464454B2E0>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 208
           │    └ <function BaseProcess._bootstrap at 0x0000004644469990>
           └ <SpawnProcess name='SpawnProcess-1:1' parent=2220 started>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x0000004644469000>
    └ <SpawnProcess name='SpawnProcess-1:1' parent=2220 started>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x00000046445704C0>, 'target': <bound method Server.run of <uvicorn.server.Server...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1:1' parent=2220 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1:1' parent=2220 started>
    │    └ <function subprocess_started at 0x00000046472820E0>
    └ <SpawnProcess name='SpawnProcess-1:1' parent=2220 started>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 8080)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x0000004644570550>>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 8080)>]
           │       │   │    └ <function Server.serve at 0x000000464720ACB0>
           │       │   └ <uvicorn.server.Server object at 0x0000004644570550>
           │       └ <function run at 0x0000004646348DC0>
           └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x00000046487AC6D0>
           │    └ <function BaseEventLoop.run_until_complete at 0x0000004646833AC0>
           └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000004646833A30>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000000464683D5A0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000046467EC280>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[True]>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...result=[True]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...result=[True]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[True]>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x0000004646D9B760>: <Task finished name='Task-136' coro=<_command() done, defined at C:\Users\Adminis...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x0000004648AA4A00>
          │            │        │    │      └ {'_prefix': {'command': ('重启',), 'raw_command': '重启', 'command_arg': [], 'command_start': ''}}
          │            │        │    └ PrivateMessageEvent(time=1656476478, self_id=3603946386, post_type='message', sub_type='friend', user_id=897528497, message_t...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x0000004648AA4940>
          │            └ <Matcher from nonebot_plugin_reboot.command, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x0000004646F78670>

> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x0000004646D9B760>: <Task finished name='Task-136' coro=<_command() done, defined at C:\Users\Adminis...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x0000004648AA4A00>
          │       │   │    │      └ {'_prefix': {'command': ('重启',), 'raw_command': '重启', 'command_arg': [], 'command_start': ''}}
          │       │   │    └ PrivateMessageEvent(time=1656476478, self_id=3603946386, post_type='message', sub_type='friend', user_id=897528497, message_t...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x0000004648AA4940>
          │       └ <function Matcher.run at 0x0000004646D9B2E0>
          └ <Matcher from nonebot_plugin_reboot.command, type=message, priority=1, temp=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x0000004646D9B760>: <Task finished name='Task-136' coro=<_command() done, defined at C:\Users\Adminis...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x0000004648AA4A00>
          │    │          │    │      └ {'_prefix': {'command': ('重启',), 'raw_command': '重启', 'command_arg': [], 'command_start': ''}}
          │    │          │    └ PrivateMessageEvent(time=1656476478, self_id=3603946386, post_type='message', sub_type='friend', user_id=897528497, message_t...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x0000004648AA4940>
          │    └ <function Matcher.simple_run at 0x0000004646D9B250>
          └ <Matcher from nonebot_plugin_reboot.command, type=message, priority=1, temp=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x0000004647EDD7E0>, params=[ModelField(name='event', type=PrivateMessageEvent, required=True)...

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': PrivateMessageEvent(time=1656476478, self_id=3603946386, post_type='message', sub_type='friend', user_id=897528497,...
                 │    └ <function _ at 0x0000004647EDD7E0>
                 └ <Dependent call=<function _ at 0x0000004647EDD7E0>, params=[ModelField(name='event', type=PrivateMessageEvent, required=True)...

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\command.py", line 16, in _
    Reloader.reload()
    │        └ <classmethod(<function Reloader.reload at 0x0000004647E1F910>)>
    └ <class 'nonebot_plugin_reboot.reloader.Reloader'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\reloader.py", line 18, in reload
    raise RuntimeError()

RuntimeError

```
[https://github.com/18870/nonebot-plugin-reboot/issues/1](url)
也是我提交的issue，系统情况一致

**Comment by 18870** [comment]
不支持 `fastapi_reload`。
另一半的回答在 #1 

使用 `fastapi_reload` 时，nonebot.run 会调用 uvicorn 再次用 spawn 的启动方式启动一个新的子进程，这个子进程里不会运行这个设置重启事件的函数（26行）

https://github.com/18870/nonebot-plugin-reboot/blob/0e91e8592c0f93542e75ea772fc772de35ec8acf/nonebot_plugin_reboot/reloader.py#L25-L27
![0](https://user-images.githubusercontent.com/22175295/176357554-e7a7b54b-95d3-4e96-b2d4-123000b4f5ef.png)

**Comment by ShadowGhost0x1a0** [comment]
好的，明儿看看
