### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by KomoriDev** [18870/nonebot-plugin-reboot#3]
似乎与 [Arcaea] (https://github.com/SEAFHMC/nonebot-plugin-arcaeabot) 不兼容

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\linxi_bot\bot.py", line 40, in <module>
    nonebot.load_plugins('plugins')
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\load.py", line 43, in load_plugins
    manager = PluginManager(search_path=plugin_dir)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 52, in __init__
    self.prepare_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 112, in prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: arcaea! Check your plugin name
```
我的 bot.py：
```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
from nonebot.adapters.qqguild import Adapter as QQ_频道Adapter
# from nonebot.adapters.ntchat import Adapter as NTCHATAdapter

# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init()
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)
driver.register_adapter(QQ_频道Adapter)
# driver.register_adapter(NTCHATAdapter)

# nonebot.load_builtin_plugins("echo")
nonebot.load_plugins('plugins')

# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
# nonebot.load_from_toml("pyproject.toml")

# Modify some config / config depends on loaded configs
# 
# config = driver.config
# do something...
if __name__ == "__mp_main__":    # 仅在子进程运行的代码
    nonebot.load_plugins('plugins')


if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.load_plugin('nonebot_plugin_reboot')
    nonebot.run(app="__mp_main__:app")

```
话说为什么我 运行 bot.py后会导入两次所有插件
```dev
FASTAPI_RELOAD=false
```

**Comment by 18870** [comment]
删除第一个`nonebot.load_plugins('plugins')`

```diff
driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)
driver.register_adapter(QQ_频道Adapter)
# driver.register_adapter(NTCHATAdapter)

# nonebot.load_builtin_plugins("echo")
- nonebot.load_plugins('plugins')

# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
# nonebot.load_from_toml("pyproject.toml")
```

**Comment by KomoriDev** [comment]
谢谢
